feat(CI): job to build unit tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,6 +58,51 @@ jobs:
             fi
           done
 
+  compilation_required:
+    name: Compilation check
+    if: ${{ github.repository != vars.MIRROR_URL }}
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    timeout-minutes: 4
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Build binary
+        run: |
+          set -e
+          
+          if [ -f Makefile ]; then
+            echo "Detected Makefile"
+            make 2>&1 | tee build.log
+          
+          elif [ -f CMakeLists.txt ]; then
+            echo "Detected CMake project"
+            cmake -B build
+            cmake --build build 2>&1 | tee build.log
+          
+          else
+            echo "No supported build system found"
+            exit 1
+          fi
+
+      - name: Upload build log
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-log
+          path: build.log
+
+      - name: Check executables
+        if: ${{ vars.EXECUTABLES != '' }}
+        run: |
+          for binary in ${{ vars.EXECUTABLES }}; do
+            if [ ! -x "$binary" ]; then
+              echo "Missing executable: $binary"
+              exit 1
+            fi
+          done
+
   check_coding_style:
     name: Coding style checking
     if: ${{ github.repository != vars.MIRROR_URL }}
@@ -155,7 +200,7 @@ jobs:
     name: Static analysis with clang tidy
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
-    needs: check_compilation
+    needs: compilation_required
     steps:
       - name: Install dependencies
         run: |
@@ -216,3 +261,30 @@ jobs:
             exit 84
           
           exit 0
+
+  unit_test:
+    name: Run unit tests
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: compilation_required
+    steps:
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y python3-pip
+          pip3 install gtest_report
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Configure CMake
+        run: |
+          cmake -B build -DCMAKE_BUILD_TYPE=Release
+
+      - name: Build binaries
+        run: cmake --build build --config Release -j 3
+
+      - name: Run tests
+        working-directory: build
+        run: |
+          ctest -V --output-junit test-results.xml || true
