feat: project setting - in progress

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,30 +76,27 @@ jobs:
         if: always()
         run: |
           if [ ! -s check.log ]; then
+            echo "No violations found"
             exit 0
           fi
           
-          echo "::notice::Style Errors found"
-          
-          echo "::group::Coding style errors"
-
+          echo "::group::Banana Map violations"
           awk '
           /\[Banana\]/ {
             file = $1
             sub(":", "", file)
-
-            level = "notice"
-            if ($0 ~ /\[Fatal\]/) level="error"
-            else if ($0 ~ /\[Major\]/) level="error"
-            else if ($0 ~ /\[Minor\]/) level="warning"
-            else if ($0 ~ /\[Info\]/) level="notice"
-
+          
+            level = "warning"
+            if ($0 ~ /\[Fatal\]/) level = "error"
+            else if ($0 ~ /\[Major\]/) level = "error"
+            else if ($0 ~ /\[Minor\]/) level = "warning"
+          
             msg = $0
             sub(/^[^:]+: \[Banana\] \[([^\]]+)\] /, "", msg)
-
+          
             printf "::%s file=%s::%s\n", level, file, msg
           }
           ' check.log
-
           echo "::endgroup::"
-          exit 84
+          
+          exit 1  # Fail job if violations found
